language: node_js

node_js:
- "10.4.1"

sudo: false

# Add your branch here to have it tested and deployed
branches:
  only:
  - master

before_install:
# Configure Git
- git config --global user.email "travis-ci@legalthings.net"
- git config --global user.name "Travis CI"

# Get all tags of git repo
- git fetch origin 'refs/tags/*:refs/tags/*'

script:
  npm run test:all

after_success:
# Bump version
- npm install mversion -g
- test "$TRAVIS_BRANCH" != 'master' -o "$TRAVIS_PULL_REQUEST" != "false" || test -n "$(git tag --contains)" || bin/bump-version

before_deploy:
# Set environment variables for deploy
- export NEW_VERSION=$(git tag --contains)
- git archive -v -o api-gateway.zip --format=zip HEAD

deploy:
  provider: releases
  api-key:
    secure: "xLjNb57LU1Xf0Bzu9w6PZIocwhFhEskCWvxYkFrxH0tz3b0+RgLBTILp/Q3gw5TKD3r2MviPqi31+gZhnLvZ8mcaL2OkssFEzKYhhJ1qEv+qxTqAAU7et4TkdN7d9v+Mc6fWuieCeDzjaZkNQ59cQ17mgG63xsus7BiYjlXq3guuycJrm4696/8kvxuC+GEkquEEIcQlIYpYP3QwRkHopo4egWDF7DtZ/wZZLUxXaImx2EGx9bvSGqzYo/wQ9OfN2PX7m1PLEh3DD27pevc1NyPYZOhYElU6iglaWgtgBETD5s/p9drK+OQ3mm9ChKzm1FQtxwJy4Jw4CK6oua6C2UQ4RytigOPMli1+we0GdoILeGb0bjXz3OcgV8yjFv22yn7lGDmUO1yHoW6/AfOIlalLMhli+S4JtWCywRzVwLKmrCBok1YvAEuhxVTAV6jOnu5PTyhccCOsJ7nPkZAr/z98W7OzzBx43G64BhO7FzrbKyGoT9z165bxTC3clcLcuE5xdqSiv+ZLxZtnJvdu5ha48nfnK8yLXNTOWGGDTR2oVG8qxLaPXBVEkuTPhME/A2nwdCZl/9ENj85YtJILZuCMrPi8wotWRiyGvgpOl47mamWoig7EoIjzqHXpFPbuIQaEA1I00VozFlp8wfZdEDd+lCIqRAtMf4XHWTguiho="
  release-number: "$NEW_VERSION"
  file: "api-gateway.zip"
  skip_cleanup: true
  on:
    branch: master