language: node_js

node_js:
- "10.4.1"

sudo: false

# Add your branch here to have it tested and deployed
branches:
  only:
  - master

before_install:
# Configure Git
- openssl aes-256-cbc -K $encrypted_d5ef11d23d78_key -iv $encrypted_d5ef11d23d78_iv -in github_deploy_key.enc -out github_deploy_key -d
- chmod 600 github_deploy_key
- eval $(ssh-agent -s)
- ssh-add github_deploy_key
- git config --global user.email "travis-ci@legalthings.net"
- git config --global user.name "Travis CI"

# Get all tags of git repo
- git fetch origin 'refs/tags/*:refs/tags/*'

script:
  npm run test:all

after_success:
# Bump version
- npm install mversion -g
- test "$TRAVIS_BRANCH" != 'master' -o "$TRAVIS_PULL_REQUEST" != "false" || test -n "$(git tag --contains)" || bin/bump-version